version: "3.2"

services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        environment:
            - discovery.type=single-node
        network_mode: "host"

    redis:
        image: redis:alpine
        network_mode: "host"

    mongo:
        image: mongo:4
        network_mode: "host"

    server:
        build: ./server
        network_mode: "host"
        volumes:
            - ./dump:/opt/newsroom/dump
        depends_on:
            - elastic
            - redis
            - mongo
        environment:
            - WEB_CONCURRENCY=2
            - WEBPACK_SERVER_URL=http://localhost:8080
            - WEBPACK_ASSETS_URL=http://localhost:8080
            - MONGO_URI=mongodb://localhost/newsroom
            - CONTENTAPI_MONGO_URI=mongodb://localhost:27017/newsroom
            - ELASTICSEARCH_URL=http://localhost:9200
            - ELASTICSEARCH_INDEX=newsroom
            - CELERY_BROKER_URL=redis://localhost:6379/1
            - REDIS_URL=redis://localhost:6379/1
            - DEFAULT_TIMEZONE=Europe/Prague
            - SECRET_KEY=newsroom
            - NEWSROOM_DEBUG=true
