web: hypercorn -c file:hypercorn_config.py newsroom.web.app:asgi_app
websocket: python -m newsroom.web.ws
worker: celery -A newsroom.web.worker.celery worker
beat: celery -A newsroom.web.worker.celery beat
newsapi: hypercorn -b "0.0.0.0:${APIPORT:-$PORT}" -w 3 newsroom.news_api.app:asgi_app
