name: "Client"

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version"
        required: false
        default: "22"
        type: string

defaults:
  run:
    working-directory: client

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
          cache-dependency-path: client/package-lock.json

      - run: npm ci
      - run: npm run build
